### ISSUE TITLE
Tome Rater Summary & Rubric Score

### ISSUE THREAD

**Issue by karl-project-review** [skiniol/pwp-capstones#6]
### Criteria 1: Valid Python Code
*_Score Level:_ 3/4 (Meets Expectations)
*_Comments:_ The provided test script runs without throwing any errors. Well done! However, with more thorough testing, UnboundLocalErrors are thrown, as described in issue #4.

### Criteria 2: Implementation of Project Requirements
*_Score Level:_ 4/4 (Exceeds Expectations)
*_Comments:_ You not only implemented all the required functions and classes, but several bonus functions and extra features in existing functions as well. Nice job! As noted in issues #2 and #3, though, some of these functions could be made more efficient by exiting loops once we have all the information we need from them. 

### Criteria 3: Software Architecture
*_Score Level:_ 4/4 (Exceeds Expectations)
*_Comments:_ All of the code relating to the required functionality is grouped into functions and classes appropriately. As described in issue #1, though, the code for checking for unique ISBNs could be refactored into a new function, but since this code is for extra functionality, I am not deducting any points.

### Criteria 4: Uses Python Language Features
*_Score Level:_ 3/4 (Meets Expectations)
*_Comments:_ For the most part, your code uses Python language features where appropriate. However, as described in issue #5, the builtin sum() function could be used to add up the elements of lists instead of writing for loops.

### Overall Score: 14/16 (Exceeds Expectations)
Good work! The majority of your code does what it should, and you succeeded in implementing not only what was required, but extra features as well. My main advice to you moving forward is to focus on making your code more efficient, using methods such as those described in issues #2 and #3. When writing code that will be used in large-scale applications, it is important that our functions not only accomplish what they are supposed to, but accomplish it reasonably quickly, and these sorts of techniques can help us with this. Again, well done on this project!

**Comment by skiniol** [comment]
Thank You, Karl for the review. 
Some of the issues I think should be obvious to me (i.e. #5 and #1) so thanks for pointing on that.
As for #2 and #3 I'll heed your advice and focus also on efficiency and not only on getting things done.
Thanks for all of your comments, I think they will be very beneficial to me.
